watch_stylesheet: true
watch_config: true

bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 34
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["clock", "active_window", "media"]
      center: ["traffic"]
      right: ["cpu", "memory", "weather", "microphone", "volume", "brightness"]
widgets:
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: "{title}"
      max_field_size:
        label: 20
        label_alt: 30
      show_thumbnail: false
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16 # Set to 0 for square corners
      icons:
        prev_track: "\udb81\udcae"
        next_track: "\udb81\udcad"
        play: "\uf04b"
        pause: "\uf04c"
      callbacks:
        on_left: "toggle_media_menu"
        on_right: "do_nothing"
    
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[process][name]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 16
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true
      callbacks:
        on_right: "do_nothing"

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %d, %b %I:%M %p}"
      label_alt: "{%A %d %B %Y, %I:%M %p}"
      #locale: 'en_EN' # Langugae for date, you can set your own, example fr_FR
      #timezones: ["America/Montreal"]
      tooltip: false
      callbacks:
        on_left: "toggle_calendar"
     
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      update_interval: 2000
      callbacks:
        on_left: "do_nothing"

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> {virtual_mem_free}"
      update_interval: 10000
      callbacks:
        on_left: "do_nothing"

  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>\uf063</span>{download_speed} <span></span> <span>\uf062</span>{upload_speed}"
      label_alt: "Download {download_speed} \ue621 Upload {upload_speed}"
      update_interval: 1000 # Update interval should be a multiple of 1000
      hide_if_offline: true
      speed_unit: "bytes"
      callbacks:
        on_left: "toggle_menu"
        on_right: "do_nothing"

  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "$env:YASB_WEATHER_API_KEY" # Get your free API key from https://www.weatherapi.com/
      update_interval: 3600 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      location: "$env:YASB_WEATHER_LOCATION" # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      tooltip: false
      callbacks:
        on_left: "toggle_card"
        on_right: "do_nothing"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzardDay: "\uebaa"
        default: "\uebaa"
        # https://www.weatherapi.com/docs/
        # Usage {temp}, {min_temp}, {max_temp}, {temp_f}, {min_temp_f}, {max_temp_f}, {location}, {humidity}, {icon}, {conditions}

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon} </span>{level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      audio_menu:
        blur: true
        round_corners: true
        show_apps: true
        show_app_icons: true
        show_apps_expanded: false
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"

  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: "<span>{icon} </span>{percent}%"
      label_alt: "Brightness {percent}%"
      tooltip: false
      hide_unsupported: true
      brightness_toggle_level: [0, 50, 100]
      auto_light: false
      auto_light_icon: "\udb80\udce1"
      auto_light_night_level: 35
      auto_light_night_start_time: "19:00"
      auto_light_night_end_time: "06:45"
      auto_light_day_level: 75
      brightness_icons: [
          "\udb80\udcde", # Icon for 0-25% brightness
          "\udb80\udcdd", # Icon for 26-50% brightness
          "\udb80\udcdf", # Icon for 51-75% brightness
          "\udb80\udce0", # Icon for 76-100% brightness
        ]
      callbacks:
        on_left: "toggle_brightness_menu"

  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "<span>{icon}</span> {level}"
      tooltip: false
      icons:
        normal: "\udb80\udf6c"
        muted: "\udb80\udf6d"
      callbacks:
        on_left: "toggle_mic_menu"
        on_right: "toggle_mute"
