[general]
import = [ "~/Git/dotfiles/other/alacritty/theme/one_dark.toml" ]

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
size = 12

[cursor]
style = { shape = "beam", blinking = "on" }

[terminal]
shell = { program = "pwsh", args = [ "--nologo" ] }

[window]
dimensions = { columns = 120, lines = 30 }
position = { x = 450, y = 180 }
padding = { x = 10, y = 10 }
dynamic_title = false
